/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppQualidadeRouteImport } from './routes/_app/qualidade'
import { Route as AppOrdensRouteImport } from './routes/_app/ordens'
import { Route as AppMaquinasRouteImport } from './routes/_app/maquinas'
import { Route as AppManutencaoRouteImport } from './routes/_app/manutencao'
import { Route as AppEstoqueRouteImport } from './routes/_app/estoque'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppApontamentosRouteImport } from './routes/_app/apontamentos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppQualidadeRoute = AppQualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensRoute = AppOrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => AppRoute,
} as any)
const AppMaquinasRoute = AppMaquinasRouteImport.update({
  id: '/maquinas',
  path: '/maquinas',
  getParentRoute: () => AppRoute,
} as any)
const AppManutencaoRoute = AppManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppApontamentosRoute = AppApontamentosRouteImport.update({
  id: '/apontamentos',
  path: '/apontamentos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/apontamentos': typeof AppApontamentosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/estoque': typeof AppEstoqueRoute
  '/manutencao': typeof AppManutencaoRoute
  '/maquinas': typeof AppMaquinasRoute
  '/ordens': typeof AppOrdensRoute
  '/qualidade': typeof AppQualidadeRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/usuarios': typeof AppUsuariosRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/apontamentos': typeof AppApontamentosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/estoque': typeof AppEstoqueRoute
  '/manutencao': typeof AppManutencaoRoute
  '/maquinas': typeof AppMaquinasRoute
  '/ordens': typeof AppOrdensRoute
  '/qualidade': typeof AppQualidadeRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/_app/apontamentos': typeof AppApontamentosRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/manutencao': typeof AppManutencaoRoute
  '/_app/maquinas': typeof AppMaquinasRoute
  '/_app/ordens': typeof AppOrdensRoute
  '/_app/qualidade': typeof AppQualidadeRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/apontamentos'
    | '/configuracoes'
    | '/estoque'
    | '/manutencao'
    | '/maquinas'
    | '/ordens'
    | '/qualidade'
    | '/relatorios'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/login'
    | '/apontamentos'
    | '/configuracoes'
    | '/estoque'
    | '/manutencao'
    | '/maquinas'
    | '/ordens'
    | '/qualidade'
    | '/relatorios'
    | '/usuarios'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/callback'
    | '/login'
    | '/_app/apontamentos'
    | '/_app/configuracoes'
    | '/_app/estoque'
    | '/_app/manutencao'
    | '/_app/maquinas'
    | '/_app/ordens'
    | '/_app/qualidade'
    | '/_app/relatorios'
    | '/_app/usuarios'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qualidade': {
      id: '/_app/qualidade'
      path: '/qualidade'
      fullPath: '/qualidade'
      preLoaderRoute: typeof AppQualidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens': {
      id: '/_app/ordens'
      path: '/ordens'
      fullPath: '/ordens'
      preLoaderRoute: typeof AppOrdensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maquinas': {
      id: '/_app/maquinas'
      path: '/maquinas'
      fullPath: '/maquinas'
      preLoaderRoute: typeof AppMaquinasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manutencao': {
      id: '/_app/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof AppManutencaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apontamentos': {
      id: '/_app/apontamentos'
      path: '/apontamentos'
      fullPath: '/apontamentos'
      preLoaderRoute: typeof AppApontamentosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApontamentosRoute: typeof AppApontamentosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppManutencaoRoute: typeof AppManutencaoRoute
  AppMaquinasRoute: typeof AppMaquinasRoute
  AppOrdensRoute: typeof AppOrdensRoute
  AppQualidadeRoute: typeof AppQualidadeRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApontamentosRoute: AppApontamentosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppManutencaoRoute: AppManutencaoRoute,
  AppMaquinasRoute: AppMaquinasRoute,
  AppOrdensRoute: AppOrdensRoute,
  AppQualidadeRoute: AppQualidadeRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
