/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemCtRouteImport } from './routes/sem-ct'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppVarejistasRouteImport } from './routes/_app/varejistas'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppQualidadeRouteImport } from './routes/_app/qualidade'
import { Route as AppOrdensRouteImport } from './routes/_app/ordens'
import { Route as AppMaquinasRouteImport } from './routes/_app/maquinas'
import { Route as AppManutencaoRouteImport } from './routes/_app/manutencao'
import { Route as AppEstoqueRouteImport } from './routes/_app/estoque'
import { Route as AppEntradaNotaFiscalRouteImport } from './routes/_app/entrada-nota-fiscal'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppApontamentosRouteImport } from './routes/_app/apontamentos'
import { Route as AppVarejistasIndexRouteImport } from './routes/_app/varejistas/index'
import { Route as AppVarejistasNovoRouteImport } from './routes/_app/varejistas/novo'
import { Route as AppVarejistasIdRouteImport } from './routes/_app/varejistas/$id'

const SemCtRoute = SemCtRouteImport.update({
  id: '/sem-ct',
  path: '/sem-ct',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVarejistasRoute = AppVarejistasRouteImport.update({
  id: '/varejistas',
  path: '/varejistas',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppQualidadeRoute = AppQualidadeRouteImport.update({
  id: '/qualidade',
  path: '/qualidade',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensRoute = AppOrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => AppRoute,
} as any)
const AppMaquinasRoute = AppMaquinasRouteImport.update({
  id: '/maquinas',
  path: '/maquinas',
  getParentRoute: () => AppRoute,
} as any)
const AppManutencaoRoute = AppManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppEntradaNotaFiscalRoute = AppEntradaNotaFiscalRouteImport.update({
  id: '/entrada-nota-fiscal',
  path: '/entrada-nota-fiscal',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppApontamentosRoute = AppApontamentosRouteImport.update({
  id: '/apontamentos',
  path: '/apontamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppVarejistasIndexRoute = AppVarejistasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVarejistasRoute,
} as any)
const AppVarejistasNovoRoute = AppVarejistasNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppVarejistasRoute,
} as any)
const AppVarejistasIdRoute = AppVarejistasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVarejistasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/sem-ct': typeof SemCtRoute
  '/apontamentos': typeof AppApontamentosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/entrada-nota-fiscal': typeof AppEntradaNotaFiscalRoute
  '/estoque': typeof AppEstoqueRoute
  '/manutencao': typeof AppManutencaoRoute
  '/maquinas': typeof AppMaquinasRoute
  '/ordens': typeof AppOrdensRoute
  '/qualidade': typeof AppQualidadeRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/varejistas': typeof AppVarejistasRouteWithChildren
  '/varejistas/$id': typeof AppVarejistasIdRoute
  '/varejistas/novo': typeof AppVarejistasNovoRoute
  '/varejistas/': typeof AppVarejistasIndexRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/sem-ct': typeof SemCtRoute
  '/apontamentos': typeof AppApontamentosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/entrada-nota-fiscal': typeof AppEntradaNotaFiscalRoute
  '/estoque': typeof AppEstoqueRoute
  '/manutencao': typeof AppManutencaoRoute
  '/maquinas': typeof AppMaquinasRoute
  '/ordens': typeof AppOrdensRoute
  '/qualidade': typeof AppQualidadeRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/': typeof AppIndexRoute
  '/varejistas/$id': typeof AppVarejistasIdRoute
  '/varejistas/novo': typeof AppVarejistasNovoRoute
  '/varejistas': typeof AppVarejistasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/sem-ct': typeof SemCtRoute
  '/_app/apontamentos': typeof AppApontamentosRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/entrada-nota-fiscal': typeof AppEntradaNotaFiscalRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/manutencao': typeof AppManutencaoRoute
  '/_app/maquinas': typeof AppMaquinasRoute
  '/_app/ordens': typeof AppOrdensRoute
  '/_app/qualidade': typeof AppQualidadeRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/varejistas': typeof AppVarejistasRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/varejistas/$id': typeof AppVarejistasIdRoute
  '/_app/varejistas/novo': typeof AppVarejistasNovoRoute
  '/_app/varejistas/': typeof AppVarejistasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/sem-ct'
    | '/apontamentos'
    | '/configuracoes'
    | '/entrada-nota-fiscal'
    | '/estoque'
    | '/manutencao'
    | '/maquinas'
    | '/ordens'
    | '/qualidade'
    | '/relatorios'
    | '/usuarios'
    | '/varejistas'
    | '/varejistas/$id'
    | '/varejistas/novo'
    | '/varejistas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/login'
    | '/sem-ct'
    | '/apontamentos'
    | '/configuracoes'
    | '/entrada-nota-fiscal'
    | '/estoque'
    | '/manutencao'
    | '/maquinas'
    | '/ordens'
    | '/qualidade'
    | '/relatorios'
    | '/usuarios'
    | '/'
    | '/varejistas/$id'
    | '/varejistas/novo'
    | '/varejistas'
  id:
    | '__root__'
    | '/_app'
    | '/callback'
    | '/login'
    | '/sem-ct'
    | '/_app/apontamentos'
    | '/_app/configuracoes'
    | '/_app/entrada-nota-fiscal'
    | '/_app/estoque'
    | '/_app/manutencao'
    | '/_app/maquinas'
    | '/_app/ordens'
    | '/_app/qualidade'
    | '/_app/relatorios'
    | '/_app/usuarios'
    | '/_app/varejistas'
    | '/_app/'
    | '/_app/varejistas/$id'
    | '/_app/varejistas/novo'
    | '/_app/varejistas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  SemCtRoute: typeof SemCtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sem-ct': {
      id: '/sem-ct'
      path: '/sem-ct'
      fullPath: '/sem-ct'
      preLoaderRoute: typeof SemCtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/varejistas': {
      id: '/_app/varejistas'
      path: '/varejistas'
      fullPath: '/varejistas'
      preLoaderRoute: typeof AppVarejistasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qualidade': {
      id: '/_app/qualidade'
      path: '/qualidade'
      fullPath: '/qualidade'
      preLoaderRoute: typeof AppQualidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens': {
      id: '/_app/ordens'
      path: '/ordens'
      fullPath: '/ordens'
      preLoaderRoute: typeof AppOrdensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maquinas': {
      id: '/_app/maquinas'
      path: '/maquinas'
      fullPath: '/maquinas'
      preLoaderRoute: typeof AppMaquinasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manutencao': {
      id: '/_app/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof AppManutencaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entrada-nota-fiscal': {
      id: '/_app/entrada-nota-fiscal'
      path: '/entrada-nota-fiscal'
      fullPath: '/entrada-nota-fiscal'
      preLoaderRoute: typeof AppEntradaNotaFiscalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apontamentos': {
      id: '/_app/apontamentos'
      path: '/apontamentos'
      fullPath: '/apontamentos'
      preLoaderRoute: typeof AppApontamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/varejistas/': {
      id: '/_app/varejistas/'
      path: '/'
      fullPath: '/varejistas/'
      preLoaderRoute: typeof AppVarejistasIndexRouteImport
      parentRoute: typeof AppVarejistasRoute
    }
    '/_app/varejistas/novo': {
      id: '/_app/varejistas/novo'
      path: '/novo'
      fullPath: '/varejistas/novo'
      preLoaderRoute: typeof AppVarejistasNovoRouteImport
      parentRoute: typeof AppVarejistasRoute
    }
    '/_app/varejistas/$id': {
      id: '/_app/varejistas/$id'
      path: '/$id'
      fullPath: '/varejistas/$id'
      preLoaderRoute: typeof AppVarejistasIdRouteImport
      parentRoute: typeof AppVarejistasRoute
    }
  }
}

interface AppVarejistasRouteChildren {
  AppVarejistasIdRoute: typeof AppVarejistasIdRoute
  AppVarejistasNovoRoute: typeof AppVarejistasNovoRoute
  AppVarejistasIndexRoute: typeof AppVarejistasIndexRoute
}

const AppVarejistasRouteChildren: AppVarejistasRouteChildren = {
  AppVarejistasIdRoute: AppVarejistasIdRoute,
  AppVarejistasNovoRoute: AppVarejistasNovoRoute,
  AppVarejistasIndexRoute: AppVarejistasIndexRoute,
}

const AppVarejistasRouteWithChildren = AppVarejistasRoute._addFileChildren(
  AppVarejistasRouteChildren,
)

interface AppRouteChildren {
  AppApontamentosRoute: typeof AppApontamentosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEntradaNotaFiscalRoute: typeof AppEntradaNotaFiscalRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppManutencaoRoute: typeof AppManutencaoRoute
  AppMaquinasRoute: typeof AppMaquinasRoute
  AppOrdensRoute: typeof AppOrdensRoute
  AppQualidadeRoute: typeof AppQualidadeRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppVarejistasRoute: typeof AppVarejistasRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApontamentosRoute: AppApontamentosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEntradaNotaFiscalRoute: AppEntradaNotaFiscalRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppManutencaoRoute: AppManutencaoRoute,
  AppMaquinasRoute: AppMaquinasRoute,
  AppOrdensRoute: AppOrdensRoute,
  AppQualidadeRoute: AppQualidadeRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppVarejistasRoute: AppVarejistasRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  SemCtRoute: SemCtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
