# Generated by Django 4.2.30 on 2026-04-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_centrodetrabaho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varejista',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail de contato.', max_length=254, verbose_name='E-mail'),
        ),
    ]
